const pages = [
    "hey, you may be wondering what this is (i did just send you a strange looking website after all).<br>i can’t tell you outright yet. but you know it’s from me (lin.)<br>so, let’s play a game.<br>there are 3 poems here. each one is written for you, about you. i’ve been working on them for a few weeks now, and i want you to follow these instructions.<br><br>1. when you’re playing this game, do <b>not</b> analyze these poems! i know that’s what you do with poetry, i know you love to do it. but i want you to focus on the writing from a solely reading-just-to-read viewpoint. for now, at least. when the game is done, go crazy. but there’s a reason i’m saying this. <br><br>2. each of these poems has part of a message i’ve encrypted. i’ve put detailed instructions on how to decode the message at the end of the poem, so you can read them, go back to the poem, and decode it. <br><br>3. decoding these messages will be extremely easy. expect that. there’s a reason i’ve made them easy.  <br><br>4. when you’re done reading the poem, type the words you decoded into the <b>indicated text section.</b> no punctuation, only spaces. don’t worry about capitalization- it isn’t case sensitive. <br><br>5. i hope you like this! <3<br><br><br>okay, that’s all from me. can’t wait to see what you think.<br><br><br>                     <b>- lin</b>",
    "i wanted to be born a star<br>but i could only be your stovelight.<br>dying too soon, flickering too early, i buzz throughout the night, noise permeating like EM fields into the empty living room.<br>burning, slowly, fizzing like a firework, burning like all good things do.<br>burning as i watch you flaring away too.<br>silent conflagration that you are. i think of how many alexandrias it would take to match your eyes, and i know that if i was a star and you were one too like in some past life, binary and forever trapped in orbit when i blinked my eyes- ever so slowly at you,<br>open and shut singing<br>.. / .-.. --- ...- . / -.-- --- ..-<br>the earthlings would look up with their telescopes, with words like \"cepheid variable\" and \"scintillation\"<br>to justify why i softened my gaze.<br>but here, but now, we are feeble and weak<br>and yet you still sit by me and linger<br>and your eyes wander to the clock at", 
    "there's a kind of flower,<br>the oxeye daisy, that<br>crops up on every patch of canadian grass in the may june juncture.<br>wedged between layers of thick toronto concrete, conscientious roots lodged in every gap like fingers<br>pressed into collarbones, tangled with dimes and<br>cigarette butts.<br>leucanthemum, sudden dawn of thought.<br>if you notice anything, it only leads you to notice more.<br>i've been taking pages from your book lately, learning to crease the corners of your mind.<br>descry is what's learnt behind fallen lips.<br>and a moving pen and mine has not been lulled since<br>the moment we spoke.<br>i map out the undergrowth with you,<br>jet-black curls tangled in your leaves, hoping we find<br>more than mere consonance hidden in the topsoil.<br>marguerite, in the wind.<br>the clock keeps me away,<br>but once you and i make it till tommorow,<br>we will buy a slice of the world.<br>we will eat it whole, using our forks just enough to seem civilized.<br>and as we lay against the earth and it carries us to friendlier fires,<br>promise me<br>you'll leave the lines etched into the pavement.",

]

document.getElementById("poem").innerHTML = pages[0];

function buttonClicked() {
    document.getElementById("input-button").innerHTML = "Test";
}